"""Synthesizes speech from the input string of text."""
import simpleaudio as sa
from google.cloud import texttospeech


def text_to_speech(txt):
    """Generates audio content for given text

    Args:
        txt (str): Text to be voiced
    """

    client = texttospeech.TextToSpeechClient()

    input_text = texttospeech.SynthesisInput(text=txt)

    voice = texttospeech.VoiceSelectionParams(
        language_code="en-US",
        name="en-US-Studio-O",
    )

    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.LINEAR16,
        speaking_rate=1
    )

    response = client.synthesize_speech(
        request={"input": input_text, "voice": voice, "audio_config": audio_config}
    )

    audio_content = response.audio_content

    play_speech(audio_content)
    # export_speech(audio_content)


def play_speech(audio_data):
    """Plays generated audio

    Args:
        audio_data (bytes): Audio content generated by text to speech API
    """
    wave_obj = sa.WaveObject(audio_data, 1, 2, 24000)
    play_obj = wave_obj.play()
    play_obj.wait_done()  # Wait until sound has finished playing


def export_speech(audio_content):
    """Exports generated audio into mp3 file

    Args:
        audio_content (bytes): Audio content generated by text to speech API
    """
    with open("output.mp3", "wb") as out:
        out.write(audio_content)
        print('Audio content written to file "output.mp3"')


if __name__ == "__main__":
    text_to_speech("Hi there")
